import { defineConfig } from "astro/config";
import react from "@astrojs/react";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  site: "https://example.com", // TODO: replace with production domain before launch
  integrations: [react()],
  vite: {
    plugins: [tailwindcss()],
  },
  redirects: {
    // Root → German home (default language)
    "/": "/de/",

    // Compatibility redirects for the old URL structure that was advertised
    // in the navbar and footer before the scaffold was merged.
    // These ensure anyone who bookmarked or shared those links still lands somewhere useful.
    // Note: /de/contact and /en/contact are omitted here because those are real
    // content pages generated by src/pages/[lang]/[slug].astro — no redirect needed.
    "/de/packages":   "/de/activities/",
    "/en/packages":   "/en/activities/",
    "/de/why-greece": "/de/region/",
    "/en/why-greece": "/en/region/",
  },
});
